@startuml
class EnemyShot {
    + EnemyShot(bulletPool:IObjectPool<Bullet>, radius:float)
    + LineShot(shooterPos:Vector3, angle:float, bulletNumber:int, moveType:Bullet.MoveType) : void
    + FanShot(shooterPos:Vector3, centerAngle:float, angleSplit:float, angleWidth:int, bulletNumber:int, moveType:Bullet.MoveType) : void
    + RoundShot(shooterPos:Vector3, angleSplit:float, shiftAngle:float, bulletNumber:int, moveType:Bullet.MoveType) : void
}
@enduml
